project:
  type: website
  output-dir: docs

website:
  title: "Rachel Roggenkemper"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: nhg_ci.qmd
        text: Negative Hypergeometric CIs
      - href: course_projects.qmd
        text: Course Projects
      - href: datafest.qmd
        text: DataFest
      - href: stat_ed_frost.qmd
        text: Statistics Education Research
      - href: 541portfolio.qmd
        text: STAT 541 Portfolio
    right: 
      - icon: github
        href: https://github.com/rroggenk/ 
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/rroggenk/ 
        aria-label: LinkedIn
      - icon: envelope
        href: mailto:rroggenk@gmail.com
        aria-label: Email

format:
  html:
    theme: 
      light: journal
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full

editor: visual

